version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "users-service"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-vhyj9jn9baj4"
s3_prefix = "users-service"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\""
