---
AWSTemplateFormatVersion: 2010-09-09

Description: >
    This template deploys the Retail Demo Store DynamoDB Tables.
    
Resources:
  ExperimentStrategyTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - 
          AttributeName: "id"
          AttributeType: "S"
        - 
          AttributeName: "feature"
          AttributeType: "S"
        - 
          AttributeName: "name"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "id"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
      GlobalSecondaryIndexes: 
        - 
          IndexName: "feature-name-index"
          KeySchema: 
            - 
              AttributeName: "feature"
              KeyType: "HASH"
            - 
              AttributeName: "name"
              KeyType: "RANGE"
          Projection: 
            ProjectionType: "ALL"

Outputs:

ExperimentStrategyTable:
    Description: DynamoDB Table for Experiment Strategies
    Value: !Ref ExperimentStrategyTable
